route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: hiteshupes@gmail.com
    from: hkshitesh@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "hkshitesh@gmail.com"
    auth_identity: "hkshitesh@gmail.com"
    auth_password: "wjbd kcza vmic bjwh"